fix(common): Require newer version of allocator (#9386)
[EqIgnoreSpan](https://github.com/swc-project/swc/blob/ec03d1ec54fc7f3acfddbb5061c2f0c75a574e91/crates/swc_common/src/eq.rs#L4)
uses the nightly_only macro, which was introduced in version 0.1.7 of
swc_allocator. When building with the older version of the allocator,
the following error results:

    error[E0432]: unresolved import `swc_allocator::nightly_only`
     --> /home/user/.cargo/registry/.../swc_common-0.36.3/src/eq.rs:4:5
      |
    4 | use swc_allocator::nightly_only;
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `nightly_only` in the root

---------

Co-authored-by: Donny/강동윤 <kdy1997.dev@gmail.com>