fix(common): Require newer version of allocator
EqIgnoreSpan uses the nightly_only macro, which was introduced in
version 0.1.7 of swc_allocator. When building with the older version
of the allocator, the following error results:

    error[E0432]: unresolved import `swc_allocator::nightly_only`
     --> /home/user/.cargo/registry/.../swc_common-0.36.3/src/eq.rs:4:5
      |
    4 | use swc_allocator::nightly_only;
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `nightly_only` in the root