Update rust-toolchain version, and fix compilation error
Updating to a newer toolchain gives the following error, due to a change
in lint behavior:

```
error: the item `swc_ecma_codegen` is imported redundantly
   --> crates/swc/src/lib.rs:135:24
    |
135 | use swc_ecma_codegen::{self, Node};
    |                        ^^^^ the item `swc_ecma_codegen` is already defined by prelude
    |
note: the lint level is defined here
   --> crates/swc/src/lib.rs:107:9
    |
107 | #![deny(unused)]
    |         ^^^^^^
    = note: `#[deny(unused_imports)]` implied by `#[deny(unused)]`
```